const mongoose = require('mongoose');

const stockStructureSchema = new mongoose.Schema({
    date: {type: Boolean},
    time: {type: Boolean},
    sl_no: {type: Boolean},
    sub_category: {type: Boolean},
    challan_no: {type: Boolean},
    item: {type: Boolean},
    batch_brand: {type: Boolean},
    batch_color: {type: Boolean},
    batch_capacity: {type: Boolean},
    batch_height: {type: Boolean},
    batch_power: {type: Boolean},
    batch_watt: {type: Boolean},
    batch_model: {type: Boolean},
    batch_form: {type: Boolean},
    batch_description: {type: Boolean},
    batch_extended_description: {type: Boolean},
    batch_location: {type: Boolean},
    seller: {type: Boolean},
    total_quantity: {type: Boolean},
    batch_no: {type: Boolean},
    batch_buy_price: {type: Boolean},
    batch_sell_price: {type: Boolean},
    per_piece_buy_price: {type: Boolean},
    per_piece_sell_price: {type: Boolean},
    batch_mfg_date: {type: Boolean},
    batch_exp_date: {type: Boolean},
    batch_warrantee_guarantee: {type: Boolean},
    batch_warrantee_guarantee_duration: {type: Boolean},
    batch_remarks: {type: Boolean},
    unique_code: {type: Boolean},
    brand: {type: Boolean},
    color: {type: Boolean},
    capacity: {type: Boolean},
    height: {type: Boolean},
    power: {type: Boolean},
    watt: {type: Boolean},
    model: {type: Boolean},
    description: {type: Boolean},
    extended_description: {type: Boolean},
    location: {type: Boolean},
    quantity: {type: Boolean},
    mfg_date: {type: Boolean},
    exp_date: {type: Boolean},
    item_buy_price: {type: Boolean},
    item_sell_price: {type: Boolean},
    warrantee_guarantee: {type: Boolean},
    warrantee_guarantee_duration: {type: Boolean},
    form: {type: Boolean},
    remarks: {type: Boolean},
    company_id: {type: mongoose.Schema.Types.ObjectId},
    updatedBy: {type: mongoose.Schema.Types.ObjectId}
}, { timestamps: true });

const StockStructure = mongoose.model('stockstructure', stockStructureSchema)
module.exports = StockStructure